import './theme-config.css' //the overrided styles of radix ui
import '@radix-ui/themes/styles.css'; //the default styles of radix ui
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './NavBar'
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import AuthProvider from './auth/provider';
import QueryClientProvider from './QueryClientProvider';

const inter = Inter({
   subsets: ['latin'],
   variable: '--font-inter'
  })
  
  export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider> 
            <Theme accentColor="purple">
              <NavBar />
              <main className='p-5'>
                <Container>    {/*to center all the pages....by default, it has max width and it centers a page*/}
                  {children}
                </Container>
              </main>
              {/* <ThemePanel /> */}
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
